project:
  type: website
  output-dir: docs

website:
  title: "portfolio"
  site-url: "https://brandon-toews.github.io/portfolio/"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/brandon-toews

format:
  html:
    theme:
        light: [cosmo, theme.scss] 
        dark: [cosmo, theme-dark.scss]
    css: styles.css
    smooth-scroll: true

editor: visual

